name: finalyearproject
description: Grade 12 Entrance Exam Preparation mobile app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  dio: ^5.9.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.1
  flutter_markdown: ^0.7.4+1
  youtube_player_flutter: ^9.1.2
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/application_log.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
